import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Next.js blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }:any) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
